theme: jekyll-theme-cayman
title: "Contextual Data Transforms"
description: "Contextual data transformation techniques: Burrows Wheeler transform, Move To Front, Run Length Encoding, Delta Encoding, Xor Delta Encoding."
author: "Ramses Alexander Coraspe Valdez"
