theme: jekyll-theme-cayman
title: "Contextual Data Transforms"
description: "The goal of this project is to identify students at risk of dropping out the school using K-Means Genetic Algorithms and ANN"
